name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/runner/apps/momentum
    steps:
      - uses: actions/checkout@v4
      - name: Update repo
        run: git pull
      - name: Stop services
        run: docker compose down --remove-orphans
      - name: Pull images
        run: docker compose pull backend frontend
      - name: Restart services
        run: docker compose up -d
